[package]
name = "pistol_scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pistol = "0.1.7"
subnetwork = "0.4.1"
